print("Hell0 World!!")
print("Hello Varsha !! Wellcome in new world !! ")
print("python is so easy !!!!")
print (2 + 3)
print(3 * 21)
print()
print("The End\n","Really is this end \n","Keed doing Practice and get good result\n",3)